version: "3"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: